<?php

function bozeak_content_permission() {
    return array(
        'administer my module' => array(
            'title' => 'Bozeaks Content Module',
            'description' => 'Perform administration tasks',
            ),
        );
}

function bozeak_content_menu() {
    $items['content/node'] = array(
            'title' => 'Bozeaks Module',
            'page callback' => 'bozeak_content_view',
            'access callback' => 'bozeak_content_permission',
        );
    
    return $items;
}

function bozeak_content_view() {
    return 'Hello';
}